apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-example
  labels:
    app: probe-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe-example
  template:
    metadata:
      labels:
        app: probe-example
    spec:
      containers:
        - name: my-container
          image: my-image:latest
          ports:
            - containerPort: 80

          # Liveness Probe - HTTP Based
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 4
