apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  completions: 3
  template:
   metadata:
    labels:
     app: myapp
   spec:
    restartPolicy: OnFailure
    containers:
     - name: mycont
       image: luksa/batch-job
