apiVersion: apps/v1
kind: Deployment
metadata:
  name: startup-probe
  labels:
    app: startup-probe-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: startup-probe-example
  template:
    metadata:
      labels:
        app: startup-probe-example
    spec:
      containers:
        - name: my-container
          image: my-image:latest
          ports:
            - containerPort: 80

          # Startup Probe - HTTP Based
          startupProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 4

