apiVersion: v1
kind: ReplicationController
metadata:
  name: mypod
spec:
    replicas: 3
    template:
      metadata:
         labels:
          app: dev
      spec:
        containers:
         - image: nginx
           name: mycont
           ports:
             - containerPort: 80

