apiVersion: v1
kind: Pod
metadata:
  name: mypod1
spec:
  containers:
    - name: mycont
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mydockersecret1
              key: MYSQL_ROOT_PASSWORD
  imagePullSecrets:
    - name: mydockersecret1
