apiVersion: batch/v1
kind: CronJob
metadata:
  name: myjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
   spec:
    template:
     metadata:
      labels:
       app: myapp
     spec:
      restartPolicy: OnFailure
      containers:
       - name: mycont
         image: luksa/batch-job
