apiVersion: v1
kind: Pod
metadata:
  name: mydbpod
spec:
  containers:
    - name: mydb
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass123
        - name: MYSQL_DATABASE
          value: mydb

