apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mypod2
spec:
    replicas: 5
    selector:
      matchLabels:
        app: dev
    template:
      metadata:
         labels:
          app: dev
      spec:
        containers:
         - image: nginx
           name: mycont
           ports:
             - containerPort: 80
