apiVersion: v1
kind: ReplicationController
metadata:
  name: mypod
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - name: mycontainer
        image: nginx
        ports:
        - containerPort: 80

