apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mypvc1
   labels:
     app: dev
spec:
  accessModes:
      - ReadWriteOnce
  resources:
   requests:
    storage: 256Mi
  selector:
    matchLabels:
      app: dev
